get:
  summary: Get app settings by id
  tags:
    - App Setting
  parameters:
    - name: app_setting_id
      in: path
      required: true
      schema:
        type: string
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/appSetting"
put:
  summary: update app settings by id
  tags:
    - App Setting
  parameters:
    - name: app_setting_id
      in: path
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          required:
            - value
          type: object
          properties:
            value:
              type: string
            key:
              type: string
    required: true
  responses:
    200:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
              result:
                type: object
  x-codegen-request-body-name: payload