version: 2
references:
  job_config: &job_config
    working_directory: ~/code
    docker:
      - image: circleci/node:8
  update_npm: &update_npm
    run:
      name: update npm
      command: sudo npm install -g npm@6.9.0
  restore_cache: &restore_cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  install_dependencies: &install_dependencies
    run:
      name: install dependencies
      command: npm install
  save_cache: &save_cache
    save_cache:
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  validate_repo: &validate_repo
    run:
      name: validate repo
      command: npm run test
jobs:
  validate:
    <<: *job_config
    steps:
      - checkout
      - *update_npm
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - *validate_repo
  deploy:
    <<: *job_config
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f5:4a:44:a1:32:8c:ee:a9:6b:96:47:0a:f5:0d:d1:4c"
      - *update_npm
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - *validate_repo
      - run:
          command: |
            git config --global user.email "thanh.pd@teko.vn"
            git config --global user.name "Phan Thanh"
      - run:
          name: build repo
          command: npm run build
      - run:
          name: deploy to github pages
          command: npm run gh-pages
workflows:
  version: 2
  nightly:
    jobs:
      - validate:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          filters:
            branches:
              only:
                - master
              ignore:
                - gh-pages
          requires:
            - validate
