post:
  tags:
    - Search
  summary: Products stock update API
  description: |
    API for Warehouse Management System to update stock information list products
    >
    Maximum count of products: 100
  requestBody:
    description: SKU of product (example 19030321)
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ListingProductWmsReq'
        example:
          18101023:
            - storeCode: B
              storeName: asdfsa
              warehouseCode: WH1
              warehouseName: Kho tổng Thái Hà
              locationCode: TH1
              locationName: Thai Ha
              proudctBizType: NEW
              available: 10
              onHand: 24
              reserved: 14
            - storeCode: B
              storeName: abcd
              warehouseCode: WH10
              warehouseName: Kho ở Trần Đại Nghĩa
              locationCode: TDN1
              locationName: Tran Dai Nghia
              proudctBizType: NEW
              available: 8
              onHand: 10
              reserved: 2
          18101056:
            - storeCode: B
              storeName: asdfsa
              warehouseCode: WH1
              warehouseName: Kho tổng Thái Hà
              locationCode: TH1
              locationName: Thai Ha
              proudctBizType: NEW
              available: 10
              onHand: 24
              reserved: 14
            - storeCode: B
              storeName: abcd
              warehouseCode: WH10
              warehouseName: Kho ở Trần Đại Nghĩa
              locationCode: TDN1
              locationName: Tran Dai Nghia
              proudctBizType: NEW
              onHand: 10
              available: 8
              reserved: 2

  responses:
    200:
      description: response for updating warehouse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingError'
          example:
            code: 'SUCCESS'
            message: 'Update successfully'
    400:
      description: error response when invalid data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingError'
          example:
            code: 'INVALID_INPUT'
            message: 'onHand property must be number, not string'
    500:
      description: response when server has error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingError'
          example:
            code: 'INTERNAL_SERVER'
            message: 'Connection to elasticsearch has troubles'
