get:
  tags:
    - Search
  summary: Product's detail API
  description: API to get all information about product by sku
  parameters:
    - name: sku
      in: path
      description: the SKU of product
      required: true
      schema:
        type: string
  responses:
    200:
      description: product object response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingSearchResp'
