get:
  tags:
    - Search
  summary: Informations of list products API
  description: API to get all information about products by list skus
  servers:
    - url: 'http://listing.teko.com/{basePath}'
      variables:
        basePath:
          default: api
  parameters:
    - name: skus
      in: query
      description: list sku, separated by commas
      required: true
      schema:
        type: string
  responses:
    200:
      description: products object response
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - result
            properties:
              code:
                type: string
                description: result code, should different from 00
              result:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      allOf:
                        - $ref: '#/components/schemas/ListingProductData'
                        - $ref: '#/components/schemas/ListingProductDetail'
    404:
      description: product not found response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingError'
          examples:
            error:
              summary: An example of 404 error
              value:
                code: "02"
                message: "404 Not Found: Product with sku 123123 is not found"

