post:
  tags:
    - Search
  summary: Products stock update API
  description: |
    API for Warehouse Management System to update stock information list products
  requestBody:
    description: SKU of product (example 19030321)
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ListingProductWmsReq'
        example:
          18101023:
            - name: asdfsa
              available: 10
              warehouseCode: WH1
              warehouseName: Kho tổng Thái Hà
              onHand: 24
              proudctBizType: NEW
              locationCode: TH1
              locationName: Thai Ha
              storeCode: B
              reserved: 14
            - name: abcd
              available: 8
              warehouseCode: WH10
              warehouseName: Kho ở Trần Đại Nghĩa
              onHand: 10
              proudctBizType: NEW
              locationCode: TDN1
              locationName: Tran Dai Nghia
              storeCode: B
              reserved: 2
          18101056:
            - name: asdfsa
              available: 10
              warehouseCode: WH1
              warehouseName: Kho tổng Thái Hà
              onHand: 24
              proudctBizType: NEW
              locationCode: TH1
              locationName: Thai Ha
              storeCode: B
              reserved: 14
            - name: abcd
              available: 8
              warehouseCode: WH10
              warehouseName: Kho ở Trần Đại Nghĩa
              onHand: 10
              proudctBizType: NEW
              locationCode: TDN1
              locationName: Tran Dai Nghia
              storeCode: B
              reserved: 2

  responses:
    200:
      description: response for updating warehouse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingSearchResp'
