post:
  tags:
    - Search
  summary: Products stock update API
  description: |
    API for Warehouse Management System to update stock information list products
    >
    Maximum count of products: 100
  requestBody:
    description: SKU of product (example 19030321)
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ListingProductWmsReq'
        example:
          - sku: 18101023
            items:
              - branch: CP02
                branchName: KINH DOANH 8
                warehouse: CP02
                warehouseName: Kho
                location: 0201
                locationName: Kho a1ng
                storeCode: B
                proudctBizType: Biz
                available: 10
                onHand: 24
                reserved: 14
                timestamp: 1558066889283.962
              - branch: CP69
                branchName: KINH DOANH 888
                warehouse: CP69
                warehouseName: Kho Trần Đại Nghĩa
                location: 0320
                locationName: Kho a1ng
                storeCode: B
                proudctBizType: NEW
                available: 8
                onHand: 10
                reserved: 2
                timestamp: 1558066889283.962
          - sku: 18101056
            items:
              - branch: CP02
                branchName: KINH DOANH 8
                warehouse: CP02
                warehouseName: Kho
                location: 0201
                locationName: Kho a1ng
                storeCode: B
                proudctBizType: Biz
                available: 10
                onHand: 24
                reserved: 14
                timestamp: 1558066889283.962
              - branch: CP69
                branchName: KINH DOANH 888
                warehouse: CP69
                warehouseName: Kho Trần Đại Nghĩa
                location: 0320
                locationName: Kho a1ng
                storeCode: B
                proudctBizType: NEW
                available: 8
                onHand: 10
                reserved: 2
                timestamp: 1558066889283.962

  responses:
    200:
      description: response for updating warehouse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingError'
          example:
            code: 'SUCCESS'
            message: 'Update successfully'
    400:
      description: error response when invalid data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingError'
          example:
            code: 'INVALID_INPUT'
            message: 'onHand property must be number, not string'
    500:
      description: response when server has error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListingError'
          example:
            code: 'INTERNAL_SERVER'
            message: 'Connection to elasticsearch has troubles'
